### ISSUE TITLE
Feature Request: Implement executeAsyncScript

### ISSUE THREAD

**Issue by juliemr** [ios-driver/ios-driver#172]
Being able to execute asynchronous script on the browser is a great feature. Would be great to have IOS Driver implement this.

Context:
https://github.com/ios-driver/ios-driver/blob/07d7b6dda73856a2306dcf71c132980ca727067e/server/src/main/java/org/uiautomation/ios/wkrdp/RemoteIOSWebDriver.java#L374

or, at least not fail when setScriptTimeout is called: https://github.com/ios-driver/ios-driver/blob/dev/common/src/main/java/org/uiautomation/ios/communication/WebDriverLikeCommand.java#L40

**Comment by teddyhwang** [comment]
+1 would love to see iOS driver be support for protractor

**Comment by samuelhorwitz** [comment]
I have implemented this feature in a fork. It still needs testing and general cleanup for a pull request but here it is. It works for what I'm doing and implements async script execution and works with Protractor.

http://www.github.com/KargoGlobal/ios-driver

**Comment by lukemadera** [comment]
+1 any update on this? This is a must have for use with Angular / Protractor!

**Comment by samuelhorwitz** [comment]
I never made a pull request because my implementation works but I am unable to get any of the tests to run and therefore unable to write my own, which is a level of polish needed for a proper PR. I haven't looked into the tests more because everything works for my purposes and I got sidetracked. If you check out my branch, and use that, everything should work as expected for Angular.

**Comment by freynaud** [comment]
Hello,
are you still interested in contributing your changes ( and sign the CLA )?
I ran the tests, and you changes are breaking : 
ExecutingJavascriptTests#testCanAccessDocumentAndWindowObjectForFrames
ExecutingJavascriptTests#testShouldBeAbleToGrabTheBodyOfFrameOnceSwitchedTo
FrameSwitchingTests#testJavaScriptShouldExecuteInTheContextOfTheCurrentFrame

In both cases, the reference to document after switching to a frame is wrong.
If you can fix those 2 tests and sign the CLA, I'm happy to merge your branch

The tests should run without having to do anything using intelliJ. Let me know if you have issues here.
thanks,
François

**Comment by samuelhorwitz** [comment]
Thanks François. I believe I have found the problem and I have committed the change. I still am unable to run tests, however. It seems to be related to Instrument's inability to connect to the simulator and maybe the MobileSafari.app file not being properly copied and modified. I have followed the instructions here https://github.com/ios-driver/ios-driver/issues/169#issuecomment-33286143 and I also run `sudo -E mvn clean test -am -pl ios-selenium-tests`. It is strange because I can build and run my real testing fine, but the Maven tests simply do not properly execute. Is there any way to the run these tests separate from Maven after the build?

Anyway, my fix:

https://github.com/KargoGlobal/ios-driver/commit/a2fb6b5a62dfa44b2287413dace606fd1f97ef17

I realized that I was referencing these arguments for `document` and `window` incorrectly. When refactoring, I left in the old way of referencing the last and second to last items in the arguments array, forgetting that now that I was getting the argument length dynamically instead of using it's length before adding new items. I have also signed the CLA.

Thank you for your help!

**Comment by freynaud** [comment]
Thanks for the CLA.

You shouldn't sudo to use ios-driver.

Can you double check that you're using xcode 5.1 and did 
http://ios-driver.github.io/ios-driver/?page=safari
 ( change rights for safari to be able to move it around )

If you still cannot , please come on IRC. You should be able to run the tests, it helps :)

**Comment by samuelhorwitz** [comment]
I was actually just going to respond, I realized it was using `sudo -E` that was causing my issues. I have all the tests running fine right now. I ran into some issues with permissions but I seem to have fixed this after recursively chmodding the directory with 777 and running the tests, allowing a folder `tmp5.0.1` to be created in the top level directory of the project. I also created a `tmp` folder in the top level directory and I set my `_JAVA_OPTIONS` environment variable to `-Djava.io.tmpdir=~/src/ios-driver/tmp`. I don't know which of these things fixed it but I do know the issue was related to tmp directories not being created by Surefire which is why I took the lazy route of using sudo to begin with.

Anyway, the tests all seem to be running now. I'm going to go on IRC anyway.

**Comment by samuelhorwitz** [comment]
I should note that I obviously reverted my frustrated `chmod -R 777` but only after all the necessary directories had been created when running a test like that.

**Comment by freynaud** [comment]
I'll check the first error here tomorrow : http://ios-driver-ci.ebaystratus.com/job/ios-selenium-tests/lastCompletedBuild/testngreports/
I think it's linked to your changes. When that's done, I'll merge.

**Comment by samuelhorwitz** [comment]
I added in testing for my code. https://github.com/KargoGlobal/ios-driver/commit/694da477dc92008187dae1dcbc741e1add311c20

For posterity, the way I managed to get individual tests to run was using the following command (for an example `className#method`): `mvn -Dtest=ExecutingJavascriptTests#testShouldBeAbleToCreateAPersistentValueAsynchronously test -pl ios-selenium-tests`

**Comment by samuelhorwitz** [comment]
I have created a pull request https://github.com/ios-driver/ios-driver/pull/233

**Comment by freynaud** [comment]
the changes have been merged.
