### ISSUE TITLE
Question about Selenium Grid (Hub) integration on Jenkins

### ISSUE THREAD

**Issue by rdissertori** [ios-driver/ios-driver#21]
Greetings,

Background:
I'm running a selenium grid as a jenkins plugin (selenium-server-standalone Grid Hub 2.25.0)
I was already able to register multiple instances of Nodes via -role node from the selenium standalone jar file on the jenkins grid (hub) and specified all capabilities in a json file needed for registering successfully via the parameter -configNode {jsonfile.json}
My achievement was to connect to the node responsible for a physical (iphone 3G) connected device, via the grid (hub) on jenkins that forwards java unit-tests to the node and do some Browser Tests on some external application (specified at the unit-test files using selenium)

Problem:
I'm having troubles registering the ios-driver node on the selenium-server standalone grid on jenkins integrated.

when I start the ios-server
java -jar ios-server-0.6.0.jar -beta -hub http://{jenkins-servername}:4444/grid/register -host 10.0.10.106 -port 5555
specifying the jenkins-server grid beeing the hub - it successfully shows up on my list at
http://{jenkins-servername}:4444/grid/console

However unlike the other nodes it shows information such as
"BaseRemoteProxylistening on http://10.0.10.106:5555test session time out after 300 sec.
Supports up to 1 concurrent tests from : "
Usually there should be a list (with icons of the browsers) of capabilities but its empty.

during the first startup of the ios-server-0.6.0 I received following errors:

29:52:698 INFO ApplicationStore.<init>  App archive folder:/Users/xxx/Development/selenium/applications
loading lib /generated/libiosdriver.jnilib
29:53:663 WARNING IPAApplication.createFrom  /Users/xxx/Development/selenium/applications/com.adobe.shadow.ipaapp added.
29:54:362 WARNING AppleLocale.findBestLocale  id isn't recognized.Please file a bug on github.You won't be able to start the app in that language.
29:55:215 INFO IOSServer.init  
Beta features enabled ( enabled by -beta flag ): true
Inspector: http://0.0.0.0:5555/inspector/
tests can access the server at http://0.0.0.0:5555/wd/hub
server status: http://0.0.0.0:5555/wd/hub/status
Connected devices: http://0.0.0.0:5555/wd/hub/devices/all
Applications: http://0.0.0.0:5555/wd/hub/applications/all
Capabilities: http://0.0.0.0:5555/wd/hub/capabilities/all
Monitoring '/Users/xxx/Development/selenium/applications' for new applications
using xcode install : /Applications/Xcode.app
using IOS version 6.1
Archived apps /Users/xxx/Development/selenium/applications
ios >= 6.0. Safari and hybrid apps are supported.
## Applications :

```
CFBundleName=Adobe Edge Inspect,CFBundleVersion=1.0.416
CFBundleName=Safari,CFBundleVersion=8536.25
```

2013-04-24 10:29:55.215:INFO::jetty-7.x.y-SNAPSHOT
2013-04-24 10:29:55.537:INFO::Started SelectChannelConnector@0.0.0.0:5555
key BoardId is null.
key ChipID is null.
29:56:262 INFO DeviceStore.onDeviceAdded  ADDED : iPhone von xxx,IOS 4.3.5[088fd27f2fbac91ae3925250a116019b7e1be522]
Exception in thread "main" org.openqa.selenium.WebDriverException: Error sending the registration request.
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.7.5', java.version: '1.7.0_04'
Driver info: driver.version: unknown
    at org.uiautomation.ios.server.grid.RegistrationRequest.registerToHub(RegistrationRequest.java:80)
    at org.uiautomation.ios.server.IOSServer.main(IOSServer.java:73)
Caused by: java.lang.RuntimeException: Error sending the registration request.
    at org.uiautomation.ios.server.grid.RegistrationRequest.registerToHub(RegistrationRequest.java:77)
    ... 1 more

but on the second time - there were no error messages at all (I supposed because the Node was still registered (in a wrong way?) on the grid)

Questions:
a) is there any way to use the ios-server-0.6.0.jar file just like the selenium server standalone file to send capabilities via a json configuration file? I'd consider this to be quite useful, because currently there is no such parameter like -configNode

b) Regarding my problem I'm quite unsure is it even possible to achieve this with the current version of the ios-server-0.6.0 or is it just not implemented to work like the way I want it to work?

To illustrate the infrastructure plan:
![structurePlan](https://f.cloud.github.com/assets/4243682/419236/5af1068c-acc7-11e2-880d-893aeb81b183.png)

**Comment by nirvdrum** [comment]
I am seeing this as well.  I'm currently running a stock Selenium 2.32.0 build for my hub.

**Comment by nicegraham** [comment]
Hi @rdissertori @nirvdrum, 

I'm not sure if you've looked at this page but it gives some insight into what's happening:
http://ios-driver.github.io/ios-driver/scale.html

Basically, we've implemented it so that ios-driver makes the initial connection and then the hub via our custom proxy polls it looking for capabilities. The thinking is that ios-driver nodes can and will form part of CI [in my usecase at least] and as such will be subject to new apps being made available. 

I realise this may not suit your needs if the nodes capabilities will not change in your usage so I will add something so that if the custom proxy isn't specified it will register the capabilities on the initial registration. 

To get you over this problem in the short term - you could build the custom proxy and use it or not use the command line switch to register and manually do it outside of ios-driver.

I'm also working on a capability matcher that is more understanding of some of the vagaries with mobile capabilites, especially when dealing with simulators which can match multiple device and os versions. 

cheers,
Graham

**Comment by nirvdrum** [comment]
Hi Graham,

Thanks for the follow-up.  I did see the part about the remote proxy, but I thought that was only necessary for any custom, native apps.  Since mobile Safari is always available, I misguidedly thought it would be part of the default capabilities.  The ordering of the docs on that page may have led to the confusion because there's a nice simple snippet for connecting to a hub, without showing how to get the proxy available on the hub.

I also thought the hub would raise an exception if the proxy wasn't available on the classpath.  But maybe that only happens at invocation time.  I'll have to take a look at the grid code.

**Comment by nicegraham** [comment]
guys, I've added capability registration in this commit:
https://github.com/ios-driver/ios-driver/commit/215dde316aeeaf297f5a65c9a2fec20eb5b3a0d9
