### ISSUE TITLE
Only committers can build

### ISSUE THREAD

**Issue by nirvdrum** [ios-driver/ios-driver#24]
The libimodule-java submodule was added using an SSH git path, meaning the only people that can clone this project and build it are those that have commit privileges.  It'd be good if non-committers could build as well.

**Comment by lukeis** [comment]
My co-worker seemed to have this problem too, it ended up that he didn't have his ssh keys on his computer associated to a github account. One can clone over ssh the repo as long as they have any GitHub user. The problem here is that if someone tries to clone the main repo over http, the submodule is defined as ssh. Thus tripping people up if they don't have their keys setup.

**Comment by nirvdrum** [comment]
AFAIK, only people set up as contributors can clone a repo over SSH and it's set up as an SSH repo here:

https://github.com/ios-driver/ios-driver/blob/master/.gitmodules#L3

**Comment by lukeis** [comment]
Nope, anyone can clone via ssh

**Comment by nirvdrum** [comment]
Ahh, well then I'll close this out.  I indeed didn't have SSH keys set up on this machine yet as I wasn't planning on committing anything.  No big deal.

**Comment by lukeis** [comment]
Clarification: anyone with a github account and ssh keys setup can clone ;)
