### ISSUE TITLE
Can you please post a link on how to build a new ios-server.jar from dev branch

### ISSUE THREAD

**Issue by apomerans** [ios-driver/ios-driver#249]
Can you please post a instructions link on how to build a new ios-server.jar from dev branch?
There was issue #187 that had the link but now it is inactive...

Thank you

**Comment by stenver** [comment]
I would also appreciate a guide for building from source.

Now that xcode 5.1.1 is out, i cant use the ios-driver since it cannot handle the new version. 

However, i noticed you guys had made commits with 5.1.1 support

When i run mvn or mvn package, i get a lot of errors, due to missing pom or jar files.

**Comment by darraghgrace** [comment]
Hey, 

Basic instructions for cloning and building the project
- git clone --recursive git@github.com:ios-driver/ios-driver.git
- cd ios-driver
- git branch (make sure you are on 'dev' or whatever branch you need. To get the dev branch, 'git checkout dev')
- mvn package -DskipTests (This will skip running the unit tests)
- jar with dependencies located in ios-driver\server\target\ios-server-standalone-0.6.6-SNAPSHOT-2014xxxx-xxxx.jar

**Comment by stenver** [comment]
Thank you :)
