### ISSUE TITLE
Testing webpages with mobile safari

### ISSUE THREAD

**Issue by ehongvc** [ios-driver/ios-driver#45]
Hi,

I am trying to automate testing of web pages on mobile safari with ipad simulator. Calling click() on a WebElement works fine, however when trying to call getLocation(), I get a server error:

org.openqa.selenium.WebDriverException: cannot find command for GET, /session/db7596f7-88c8-470d-ad00-d3055a111024/element/1_9/location

It seems to me that some functionalities of WebElement isn't available but I might be mistaken. 

Is there another approach to getting the location of a html element? Ultimately, I would like to perform drag or page scroll.

Thanks!

**Comment by nicegraham** [comment]
Hi, 

the getLocation() has been added since the 0.6.0, so if you take the latest code from the dev branch it will be there. 

You can see some examples of native actions here https://github.com/ios-driver/ios-driver/blob/dev/ios-selenium-tests/src/test/java/org/uiautomation/ios/selenium/interactions/touch/TouchFlickTest.java

graham
