### ISSUE TITLE
Question: Any plans to make this available for .NET?

### ISSUE THREAD

**Issue by ravindraupadhya** [ios-driver/ios-driver#52]
We have built all of our automation stack using .NET and Selenium WebDriver. We are looking to use ios-server to automation iPad Hybrid apps and Safari on iPad.

I was able to translate (through ikvmc) and include the ios-server jar file as a reference in our .NET project. However, the implementations and namespaces you have conflict with Selenium WebDriver's namespace.

Are there any plans to make this available and working for .NET consumers?

**Comment by freynaud** [comment]
can you explain where the conflict is ? Ideally you project should NOT depend on ios-driver, as ios-driver is the Remote/Server part. I assume your automation stack is about writing the test cases, that should only depend on the webdriver client.
What are the specific issues for .Net. We implement the webdriver protocol specifically so that we can reuse the webdriver clients as is, without having to add anything in the ios-driver project itself.

thanks,
François

**Comment by ravindraupadhya** [comment]
My bad - Jumped the gun!

When I looked at the sample code and saw IOSCapabilities.iphone("UICatalog") I assumed that this is some new/added functionality for launching and managing apps which is present in new set of client side bindings made available only in java.

I looked at the metadata for IOSCapabilities and figured that I should be using:
DesiredCapabilities capabilities = DesiredCapabilities.IPad();
capabilities.SetCapability("CFBundleName", "MyAppName");

Thank you very much, appreciate your prompt response.

Keep up the excellent work!
