### ISSUE TITLE
ios-driver does not handle unsigned SSL Certificates on safari

### ISSUE THREAD

**Issue by mirmfl** [ios-driver/ios-driver#96]
ios driver does not handle unsigned SSL Certificates on safari. Need a way to accept unsigned SSL Certificates.

**Comment by krmahadevan** [comment]
While the permanent fix is being worked out, the following should do the trick.

String url = "http:/mydomain.com"
driver.executeScript("window.location=arguments[0]; ",url);
driver.switchTo().alert().accept();

Here the idea is to use javascript to load the URL instead of using driver.get()
Then use the alert() to switch to the alert [ the native handling of IOSDriver comes into picture here] and then accept it.

Our test environments makes use of blanket self signed certificates and this worked for me. Hope that helps

**Comment by mirmfl** [comment]
Hi Krishnan,

I tried doing the following but I got the error: "AttributeError: 'WebDriver' object has no attribute 'executeScript'"

url = "http://mydomain.com"

driver = webdriver.Remote("http://localhost:4444/wd/hub", webdriver.DesiredCapabilities.IPHONE)

driver.executeScript("window.location=arguments[0]",url)

driver.switchTo().alert().accept();

Am I doing this right?

Thanks

**Comment by lukeis** [comment]
((JavascriptExecutor)driver).executeScript("windows.location = arguments[0]", url);

**Comment by mirmfl** [comment]
Found it. I am using Python so I had to do:

driver.execute_script("window.location=arguments[0]","http://myurl")

driver.switch_to_alert().accept()

Your suggestion worked. Thanks for your help! You pointed me in the right direction.

**Comment by sashank1** [comment]
krmahadevan
hi ..  this 
String url = "http:/mydomain.com"
driver.executeScript("window.location=arguments[0]; ",url);
driver.switchTo().alert().accept();

din"t work in my case..
in middle of web page test
 like

http://www.realcme.org/cms/play/267781#3
.... where #3  is the third page ...where i get alert while navigating to this page...

any solution as if now 
it tried these
1) dblclick no use..
2)java script dom events..no use..

when i searched i got this patch 

http://code.google.com/p/selenium/issues/detail?id=3862
but din"t help my case..

please provide if any solution available...
Thanx a ton in advance....

**Comment by sashank1** [comment]
krmahadevan
hi ..  this 
String url = "http:/mydomain.com"
driver.executeScript("window.location=arguments[0]; ",url);
driver.switchTo().alert().accept();

din"t work in my case..
in middle of web page test
 like

http://www.realcme.org/cms/play/267781#3
.... where #3  is the third page ...where i get alert while navigating to this page...

any solution as if now 
it tried these
1) dblclick no use..
2)java script dom events..no use..

when i searched i got this patch 

http://code.google.com/p/selenium/issues/detail?id=3862
but din"t help my case..

please provide if any solution available...
Thanx a ton in advance....

**Comment by krmahadevan** [comment]
THis issue was with respect to handling certificate issues [ self signed ones ].
I dont quite understand as to how you are getting a certificate exception in the middle of your flow.

You will have to add more clarity to what exactly are you trying to accomplish here

**Comment by sashank1** [comment]
hi..  krmahadevan .. am not getting any security exception.... what exactly my scenario is 
: i  need to take a test that  navigates to next page after  filling answers and clicking next button  , so when i navigate from 2 page to 3rd page in the test, after clicking next  button a popup appears ,then i need to accept it in order to move to next page..if i don"t accept it doesn"t goes to next page(where pop up accept is mandatory) 

i tried this  when am in 2nd page
: ((JavascriptExecutor)context.webDriver()).executeScript("window.location=arguments[0]; ","http://www.realcme.org/cms/play/267781#3");

```
context.webDriver().switchTo().alert().accept();
```

i got following error
: Caused by: org.openqa.selenium.NoAlertPresentException: The SafariDriver does not support alert handling. To prevent tests from handing when an alert is opened, they are always immediately dismissed.

**Comment by krmahadevan** [comment]
I dont know what can be done to get past this problem, but basically you seem to be tying yourself to the wrong issue to begin with. As the title of this bug states, this is with respect to handling certificate issues, whereas you seem to be talking about something else.

**Comment by freynaud** [comment]
driver.switchTo().alert().accept(); will click the alert.

**Comment by krmahadevan** [comment]
@freynaud 
Francois, 
Does iosdriver also take care of dealing with self signed certs like the other WebDrivers or is it that ios driver will not deal with cert exceptions ?

**Comment by freynaud** [comment]
ideally, the system under tests should be properly configured. That's the recommended way :)
If it's not, you can use the 
cap.setCapability(CapabilityType.ACCEPT_SSL_CERTS,true);
or
start the server specifying the -trustStore option and specify your trust store

**Comment by SerinaTan** [comment]
@lukeis 
Hello,
I am using Java to write my test so I tried ((JavascriptExecutor)driver).executeScript("windows.location = arguments[0]", url);
but I got an exception saying JS error :ReferenceError: Can't find variable: windows.

I also tried simply driver.switchTo().alert().accept(); but it didn't find an alert at all.

I am trying to get rid of the "allow to use my location" alert on the webpage.

I would really appreciate it if you could give me some help on this!

Serina

**Comment by lukeis** [comment]
window.location  not windows... sorry for the typo in my original response.

**Comment by SerinaTan** [comment]
@lukeis 
Hi, no worries! Thanks for your reply.
This time the exception is gone but driver.switchTo().alert() returns me an error saying the alert has no text on it. But I can see the "Allow to use location" pop up when I am testing on mobile Safari. Do you have any idea how to deal with this? 

Thanks a lot!
Serina
